export const GRAPH_RAG = {
  CHUNK_ENTITY_LIMIT: 8,
  TITLE_ENTITY_WEIGHT: 3,
  TAG_ENTITY_WEIGHT: 2,
  TERM_ENTITY_WEIGHT: 1,
  DIRECT_ENTITY_MATCH_BOOST: 4,
  RELATION_MATCH_BOOST: 2,
  CONTENT_TOKEN_MATCH_BOOST: 1,
  TOP_K: 3,
  MAXIMUM_MATCHES_PER_SLUG: 1,
  GRAPH_QUERY_PATTERNS: [
    '전체',
    '공통',
    '철학',
    '기조',
    '관통',
    '반복',
    '경향',
    'overall',
    'common',
    'across',
    'philosophy',
    'entire blog',
    'whole blog',
  ],
} as const
