export const POST_SEARCH = {
  INTRO_SECTION_SLUG: 'intro',
  EXCERPT_MAX_LENGTH: 220,
  CONTENT_MAX_LENGTH: 1200,
  CONTENT_CHUNK_OVERLAP_LENGTH: 160,
  CONTENT_CHUNK_BOUNDARY_SEARCH_RATIO: 0.65,
  CONTENT_CHUNK_IDENTIFIER_SUFFIX: '-part-',
  HEADING_DEPTHS: {
    SECTION: 2,
    SUBSECTION: 3,
  },
} as const
