export const SEMANTIC_SEARCH = {
  SEARCH_TERM_LIMIT: 24,
  MINIMUM_TOKEN_LENGTH: 2,
  STOP_WORDS: {
    en: [
      'a',
      'an',
      'and',
      'are',
      'for',
      'from',
      'how',
      'in',
      'is',
      'of',
      'on',
      'or',
      'that',
      'the',
      'this',
      'to',
      'use',
      'what',
      'which',
      'with',
      'you',
    ],
    ko: ['그리고', '그런데', '에서', '으로', '이거', '이건', '정리', '하는', '했다'],
  },
  TERM_GROUPS: [
    ['react-query', 'react query', 'tanstack query', 'tanstack-query'],
    ['next.js', 'nextjs', 'next js'],
    ['typescript', 'type script'],
    ['tech stack', '기술 스택', '기술스택'],
    ['career', 'experience', '경력', '커리어'],
    ['education', 'university', 'school', '학력', '전공'],
    ['project', 'projects', '프로젝트', 'side project', 'portfolio'],
  ],
} as const
